version: '3.5'

services:

  traefik:
   image: "traefik:v2.3.1"
   container_name: traefik
   ports:
     - 80:80
     - 8080:8080
     - 443:443
   command:
      #- "--log.level=DEBUG"
#      - "--api.insecure=true"
#      - "--providers.docker=true"
#      - "--providers.docker.exposedbydefault=false"
#      - "--entrypoints.web.address=:80"
#      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
#      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
#      - "--entrypoints.web.http.redirections.entrypoint.to=web-secure"
#      - "--entrypoints.web-secure.address=:443"
#      - "--entrypoints.web-secure.forwardedHeaders=false"
#      - "--certificatesresolvers.le.acme.dnschallenge=true"
#      - "--certificatesresolvers.le.acme.dnschallenge.provider=namecheap"
#      - "--certificatesresolvers.le.acme.dnschallenge.resolvers=1.1.1.1:53"
#      - "--certificatesresolvers.le.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
#      - "--certificatesresolvers.le.acme.email=quickrunner1988@gmail.com"
#      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
   volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /docker/docker-compose-files/traefik/config/traefik.yml:/etc/traefik/traefik.yml
      - /docker/docker-compose-files/traefik/config/letsencrypt:/letsencrypt
      - /docker/docker-compose-files/traefik/config/logs:/logs
   labels:
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.rule=Host(`traefik.wiesefamily.io`)
      - traefik.http.routers.traefik.tls.certresolver=le
      - traefik.http.routers.traefik.tls.domains[0].main=wiesefamily.io
      - traefik.http.routers.traefik.tls.domains[0].sans=*.wiesefamily.io,wiesefamily.io
      - traefik.http.routers.traefik.entrypoints=web-secure
      - traefik.docker.network=traefik_net
   env_file: /docker/docker-compose-files/traefik/traefik.env
   networks:
     traefik_net:

networks:
  traefik_net:
    external: true